[versions]
runelite = "latest.release"
runelite-arn = "latest.release"
lombok = "1.18.30"
guice = "4.1.0"
pf4j = "3.6.0"
javax-annotation = "1.3.2"
storm-api = "0.0.4-SNAPSHOT"
storm-sdk = "0.0.4-SNAPSHOT"

[libraries]
runelite-client = { module = "net.runelite:client", version.ref = "runelite" }
runelite-api = { module = "net.runelite:runelite-api", version.ref = "runelite" }
runelite-arn = { module = "net.runelite.arn:http-api", version.ref = "runelite-arn" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
pf4j = { module = "org.pf4j:pf4j", version.ref = "pf4j" }
javax-annotation = { module = "javax.annotation:javax.annotation-api", version.ref = "javax-annotation" }
storm-api = { module = "net.storm:storm-api", version.ref = "storm-api" }
storm-sdk = { module = "net.storm:storm-sdk", version.ref = "storm-sdk" }